/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cz.gvid.kripac.edvm.ui;

import java.awt.Color;

/**
 * Represents tape cell
 * @author majkel
 */
public class Cell extends javax.swing.JPanel {

    /**
     * Creates new form Cell
     */
    public Cell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        value = new javax.swing.JLabel();
        id = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        value.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        value.setText("0");
        jPanel1.add(value, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jPanel1, gridBagConstraints);

        id.setText("0:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(id, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets id of current cell 
     * @param id cell id 
     * @return self 
     */
    public Cell setId(int id) {
        this.id.setText(id + ":");
        return this;
    }
    
    /**
     * Sets cell value 
     * @param value of cell 
     * @return self 
     */
    public Cell setValue(int value) {
        this.value.setText(value + "");
        return this;
    }
    
    /** 
     * Sets background color of cell 
     * @param color of cell 
     * @return self
     */
    public Cell highlight(Color color) {
        this.setBackground(color);
        this.jPanel1.setBackground(color);
        return this;
    }
    
    /**
     * Clears background color
     * @return self
     */
    public Cell clear()  {
        return this.highlight(Color.DARK_GRAY);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
