/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cz.gvid.kripac.edvm.ui;

import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author majkel
 */
public class FileSelector extends javax.swing.JPanel {

    private UI ui;
    
    /**
     * Creates new form FileSelector
     */
    public FileSelector(UI ui) {
        this.ui = ui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        selectFile = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setLayout(new java.awt.GridBagLayout());

        selectFile.setFont(new java.awt.Font("Source Code Pro", 0, 13)); // NOI18N
        selectFile.setText("Select file");
        selectFile.setAlignmentY(0.0F);
        selectFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileActionPerformed(evt);
            }
        });
        add(selectFile, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        var file = fc.getSelectedFile();
        ui.runSimulator(file);
    }//GEN-LAST:event_selectFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton selectFile;
    // End of variables declaration//GEN-END:variables
}
